#!/bin/bash
# Create by Benyamin-creator
# github: https://github.com/Benyamin-creator
# Gitlab: https://gitlab.com/RED-SOCIAL
# Youtube: Benyamin 2000

# Colors
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"

echo -e "$green "
clear
sleep 0.1
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
figlet BIENVENIDO A REDTOOLS
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 0.4
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			Create by Benyamin-creator"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
sleep 0.4
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			.......5%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			............10%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			.................20%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			........................30%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "			..............................55%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                  ....................................75%"
sleep 0.1
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                  .......................................100%"
sleep 0.2
clear
echo -e "\033[1;33m"
clear
# banner
figlet  RedTools
echo -e "$green[$red*$green] $Purple Create by Benyamin-creator"
echo -e "$green[$red*$green] $Purple YouTube : Benyamin 2000"
sleep 0.4
echo -e "$red ------------------------"
echo -e "$red|$green  Select a menu option: $red|$nc"
echo -e "$red ------------------------"
echo -e "$Purple [$yellow 01 $Purple] $Cyan DayFish"
echo -e "$Purple [$yellow 02 $Purple] $Cyan DayFish1.1"
echo -e "$Purple [$yellow 03 $Purple] $Cyan RedFish"
echo -e "$Purple [$yellow 04 $Purple] $Cyan FRI3NDS"
echo -e "$Purple [$yellow 05 $Purple] $Cyan FACTORY"
echo -e "$Purple [$yellow 06 $Purple] $Cyan HACK-CAM"
echo -e "$Purple [$yellow 07 $Purple] $Cyan F-BRUTE"
echo -e "$Purple [$yellow 08 $Purple] $Cyan IP-E"
echo -e "$Purple [$yellow 09 $Purple] $Cyan D-FB1"
echo -e "$Purple [$yellow 10 $Purple] $Cyan A-DOS"
echo -e "$Purple [$yellow 11 $Purple] $Cyan BF-GMAIL"
echo -e "$Purple [$yellow 12 $Purple] $Cyan FB-INFORMATION"
echo -e "$Purple [$yellow 13 $Purple] $Cyan FotoSploit"
echo -e "$Purple [$yellow 14 $Purple] $Cyan SocialSploit"
echo -e "$Purple [$yellow 15 $Purple] $Cyan infectador-framework"
echo -e "$Purple [$yellow 16 $Purple] $Cyan Spayer"
echo -e "$Purple [$yellow 17 $Purple] $Cyan scam"
echo -e "$Purple [$yellow 18 $Purple] $Cyan NgrokTH"
echo -e "$Purple [$yellow 19 $Purple] $Cyan DICTIONARY-GENERATOR"
echo -e "$Purple [$yellow 20 $Purple] $Cyan Email-Supplant"
echo -e "$Purple [$yellow 30 $Purple] $Cyan TOOLS-KILLER-ON-THE-NET"
echo -e "$green ●-------------------●"
echo -e "$green | $blue  EXTRAS OPTIONS $green |"
echo -e "$green ●-------------------●"
echo -e "$Purple [$yellow 98 $Purple] $Cyan AYUDA $red($yellow HELP $red)"
echo -e "$Purple [$yellow 99 $Purple] $Cyan SALIR $red($yellow EXIT $red)"
echo -e "$Purple [$yellow 100 $Purple] $Cyan LISTA DE COMANDOS $red($yellow COMANDOS $red)"
echo ""
echo -e "$red (Choose an option): "
echo -e "$green"
read -p "ELIJA UNA OPCION ==> " ch


if [ $ch = 01 ] || [ $ch = 1 ] ; then
clear
echo -e $green" Installing DayFish "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/DayFish
echo -e $green" Done Install Cuk "
fi

if [ $ch = 02 ] || [ $ch = 2 ] ; then
clear
echo -e $green" Installing DayFish1.1 "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/DayFish1.1
echo -e $green" Done Install Cuk "
fi

if [ $ch = 03 ] || [ $ch = 3 ] ; then
clear
echo -e $green" Installing RedFish "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/RedFish
echo -e $green" Done Install Cuk "
fi

if [ $ch = 04 ] || [ $ch = 4 ] ; then
clear
echo -e $green" Installing FRI3NDS "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/FRI3NDS
echo -e $green" Done Install Cuk "
fi

if [ $ch = 05 ] || [ $ch = 5 ] ; then
clear
echo -e $green" Installing FACTORY "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/FACTORY
echo -e $green" Done Install Cuk "
fi

if [ $ch = 06 ] || [ $ch = 6 ] ; then
clear
echo -e $green" Installing HACK-CAM "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/HACK-CAM
echo -e $green" Done Install Cuk "
fi

if [ $ch = 07 ] || [ $ch = 7 ] ; then
clear
echo -e $green" Installing F-BRUTE "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Benyamin-creator/F-BRUTE
echo -e $green" Done Install Cuk "
fi

if [ $ch = 08 ] || [ $ch = 8 ] ; then
clear
echo -e "$green Installing IP-E"
sleep 1
apt update && apt upgrade
apt install python
apt install php
apt install git
git clone https://github.com/Benyamin-creator/IP-E
echo -e "$green Done Install Cuk"
fi

if [ $ch = 09 ] || [ $ch = 9 ] ; then
clear
echo -e "$green Installing D-FB1"
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github/Benyamin-creator/D-FB1
echo -e "$green Done Install Cuk"
fi

if [ $ch = 10 ] ; then
clear
echo -e "$green Installing A-DOS"
sleep 1
apt update && apt upgrade
apt install php
apt install python
git clone https://github.com/Benyamin-creator/A-DOS
echo -e "$green Done Install Cuk"
fi

if [ $ch = 11 ] ; then
clear
echo -e "$green Installing BF-GMAIL"
sleep 1
apt update && apt upgrade
apt install php
apt install bash
apt install git
git clone https://github.com/Benyamin-creator/BF-GMAIL
echo -e "$green Done Install Cuk"
fi

if [ $ch = 12 ] ; then
clear
echo -e "$green Installing FB-INFORMATION"
sleep 1
apt update && apt upgrade
apt install python
apt install php
apt install git
git clone https://github.com/Benyamin-creator/FB-INFORMATION
echo -e "$green Done Install Cuk"
fi

if [ $ch = 13 ] ; then
clear
echo -e "$green Installing FotoSploit"
sleep 1
apt update && apt upgrade
apt install php
apt install bash
apt install git
git clone https://github.com/Cesar-Hack-Gray/FotoSploit
echo -e "$green Done Install Cuk"
fi

if [ $ch = 14 ] ; then
clear
echo -e "$green Installint SocialSploit"
sleep 1
apt update && apt upgrade -y
pkg install php
pkg install bash
pkg install -y git
git clone https://github.com/Cesar-Hack-Gray/SocialSploit
echo -e "$green Done Install Cuk"
fi

if [ $ch = 15 ] ; then
clear
echo -e "$green Installing infectador-framework"
sleep 1
apt update && apt upgrade -y
apt install php
apt install bash
apt install git
git clone https://github.com/Cesar-Hack-Gray/infectador-framework
echo -e "$green Done Install Cuk"
fi

if [ $ch = 16 ] ; then
clear
echo -e "$green Installing Spayer"
sleep 1
apt update && apt upgrade -y
apt install php
apt install git
git clone https://github.com/Cesar-Hack-Gray/Spayer
echo -e "$green Done Install Cuk"
fi

if [ $ch = 17 ] ; then
clear
echo -e "$green Installing scam "
sleep 1
apt update && apt upgrade -y
apt install php
apt install git
git clone https://github.com/Cesar-Hack-Gray/scam
echo -e "$green Done Install Cuk"
fi

if [ $ch = 18 ] ; then
clear
echo -e "$green Installing NgrokTH"
sleep 1
apt update && apt upgrade -y
termux-setup-storage
pkg install -y git
git clone https://github.com/TermuxHacking000/NgrokTH
echo -e "$green Done Install Cuk"
fi

if [ $ch = 19 ] ; then
clear
echo -e "$green Installing DICTIONARY-GENERATOR"
apt update && apt upgrade
pkg install python
pkg install php
pkg install git
git clone https://github.com/Benyamin-creator/DICTIONARY-GENERATOR
echo -e "$green Done Install Cuk"
fi

if [ $ch = 20 ] ; then
clear
echo -e "$green Installing Email-Supplant"
apt update && apt upgrade
pkg install python
pkg install php
pkg install git
git clone https://github.com/Benyamin-creator/Email-Supplant
echo -e "$green Done Install Cuk"
fi

if [ $ch = 21 ] ; then
clear
echo -e "$green Installing VIRUS-CREATE"
apt update && apt upgrade
pkg install python
pkg install php
pkg install git
git clone https://github.com/Benyamin-creator/VIRUS-CREATE
echo -e "$green Done Install Cuk"
fi

if [ $ch = 30 ] ; then
clear
echo -e "$green Installing TOOLS-KILLER-ON-THE-NET"
sleep 1
apt update && apt upgrade
apt install bash
apt install php
apt install git
git clone https://github.com/Benyamin-creator/TOOLS-KILLER-ON-THE-NET
echo -e "$green Done Install Cuk"
fi

if [ $ch = 98 ] ; then
clear
echo -e "$yellow ESPERE UN MOMENTO POR FAVOR"
sleep 1
nano AYUDA.txt
fi

if [ $ch = 100 ] ; then
clear
echo -e "$red MOSTRANDO COMANDOS SECUNDARIOS (HERRAMIENTAS)"
sleep 1
nano COMANDOS.sh
fi

if [ $ch = 99 ] ; then
clear
echo ""
sleep 1
echo ""
echo -e "$green[$red*$green] $yellow CREATE BY BENYAMIN-CREATOR"
sleep 1
echo ""
echo -e "$green[$red*$green] $yellow BYE "
sleep 1
exit
fi
